### ISSUE TITLE
Assay to measure PLCz1 activity

### ISSUE THREAD

**Issue by EveCarter** [StructuralGenomicsConsortium/CNP5-PLCZ1#1]
A key requirement for finding an inhibitor of PLCz1 is to have an assay that will measure the activity of the protein against different compounds. 

Previously used PLC activity assays use tritium labelled phosphatidylinositol 4,5-biphosphate (PIP2), as the protein is known to hydrolyse PIP2 into inositol-1,4,5-triphosphate (IP3) and diacylglycerol (DAG). The results are quantified using liquid scintillation spectrofluorimetry.
J. Biol. Chem. 2005, 280(35), 31011–31018 [doi:10.1074/jbc.M500629200](https://www.jbc.org/article/S0021-9258(20)79374-9/fulltext)
Biochem. J. 2017, 474, 1003–1016 [doi:10.1042/BCJ20161057](https://pubmed.ncbi.nlm.nih.gov/28270562/)

There are some commercially available colorimetric assays that provide a chromogenic compound and lyophilised PLC which can be mixed with a tissue sample and provide colorimetric measurement of activity at 405 nm.
[https://www.abcam.com/phospholipase-c-activity-assay-kit-colorimetric-ab273343.html](https://www.abcam.com/phospholipase-c-activity-assay-kit-colorimetric-ab273343.html)

We would rather not work with radioactive compounds and, due to the large number of activity tests we plan on doing, the commercial option is probably too expensive, therefore an alternative assay would be desired.

**Comment by mattodd** [comment]
Interesting. I think we need help here from some of the assay folks elsewhere in the group, as well as Karl Swann's group in Cardiff. Let's see if we can get some of them on here to advise. Agree that fluorometric WAY preferable to radiolabelled.

**Comment by EveCarter** [comment]
A discussion with Matilda Katan has highlighted another assay to measure PLC activity. It uses commercially available [Aldol 518](https://www.biosynth.com/p/EA175486/2484873-17-6-aldol-518-myo-inositol-1-phosphat) as a substrate for hydrolysis and [Aldol 355](https://www.biosynth.com/p/EA175365/2484872-84-4-aldol-355-fluorescence-enhancer) as a fluorescence enhancer. Hydrolysis was measured in a continuous format with excitation at 510 nm and emission filter at 618 nm.
* Sci. Adv. 2022, 8 (25), 1-16 [doi:10.1126/sciadv.abp9688](https://www.science.org/doi/10.1126/sciadv.abp9688)

**Comment by EveCarter** [comment]
Closing as this issue has been resolved. The relevant information and a link to this issue has been included on the wiki [here](https://github.com/StructuralGenomicsConsortium/CNP5-PLCZ1/wiki/What-is-Known#plc-assays).
