### ISSUE TITLE
PLCz1 Open Online Meeting - Tue July 4th

### ISSUE THREAD

**Issue by AnnaGirtle** [StructuralGenomicsConsortium/CNP5-PLCZ1#10]
**Date:** Tue July 4th 2023
 **Time:** 2pm UK time ([other times](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2023&month=7&day=4&hour=13&min=0&sec=0&p1=136&p2=250&p3=37&p4=239&p5=235&p6=152&p7=770&p8=43&p9=240))
 **Place:** [Zoom link](https://ucl.zoom.us/j/92810058430?pwd=R2lnT3JjY2tLWHAyMDJ6WjgranpaZz09)
**Previous Meeting:** issue #9 
 **Who can come?:** Anyone. No need to say anything unless you'd like to. If you'd like to contribute, please join Github.

_Attendees:_ Prof Al Edwards (SGC), Prof Opher Gileadi (SGC), Dr Eve Carter (UCL), Dr Madison Edwards (Uni Toronto), Dr Claudia Tredup (Goethe-University Frankfurt), Dr Nico Braeuer (Nuvisan), Anna Girtle (UCL)

_Decks_: [Opher and Eve's presentation.pptx](https://github.com/StructuralGenomicsConsortium/CNP5-PLCZ1/files/12343351/2023-07-04.open.meeting.7.mostly.Opher.s.pptx)

### Agenda:

**1) Protein Production**
- Update from Madison Edwards, [@EveCarter](https://github.com/EveCarter), and Opher Gileadi

**In meeting:**

Opher outlined the protein modification work he has been exploring. First attempt purification of the modified protein using a N-terminal tag resulted in loss of most of protein. Expression experiments in E. coli were performed using PLCz1 with a C-terminal strep tag. This resulted in recovery of PLCz1, likely associated with GroEL. This result is not very promising but Opher will try to remove GroEL and test protein complex for activity. Mammalian expression was tested in HEK cells, but native human PLCz1 gave no expression. The artificial codon-optimized gene does however give expression by flag-tag immunoblot, with the size of the protein bands corresponding to the loss of the N-terminal region. This was the first detectable expression, and follow-up will include cloning the gene into a better expression vector and changing the flag-tag to a strep-tag. He does have a protein recovered from streptactin chromatography but is waiting on mass spec results to verify identify. He then plans to send the protein for assay by the end of July, optimize expression and recovery by end of August, and optimize stability. In addition, Opher is procuring a similar construct for baculovirus with relevant sequence optimization as yields of intracellular proteins in insects is usually higher than in mammals.

Aled commented that Madison has a protein that is good enough for secondary assay, so getting a new expression system is perhaps not the most important thing at this time. He suggests Claudia performing an in-cell target engagement assay with compounds from Nuvisan's screen would be an incredibly important next step.

Nico updated that Nuvisan has the IP1 and XY69 assays up and running, finding the mouse and rhesus proteins are nicely active. He also notes that there is a good correlation between human and mice results thus far, but the most promising compounds are in the triple digit nanomolar range. Nuvisan is working on setting up an IVF assay, but there is limited throughput. They have also started some crystallization of rat PLCz1.

Eve presented preliminary data for the aldol assay. She found it does seem to work with PLCz1 and will try to optimize it further as it is cheap and easy to perform.

**2) Any other business**

_L'esprit de l'escalier_
If you'd like to follow up after the meeting, please comment below. You can also email, but please be clear if anything in the email should not be public domain - the default is open.

**Comment by mattodd** [comment]
Just to say I'm an apology today - conference. Looking forward to hearing about latest protein news, and I guess we need to (soon) delineate our various options for identifying hit compounds if the protein continues to look promising. Happy 4th July to absent US friends.
