### ISSUE TITLE
PLCz1 Open Online Meeting - Tue Oct 10th

### ISSUE THREAD

**Issue by AnnaGirtle** [StructuralGenomicsConsortium/CNP5-PLCZ1#13]
**Date:** Tue October 10th 2023
 **Time:** 1pm UK time ([other times](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2023&month=10&day=10&hour=12&min=0&sec=0&p1=136&p2=250&p3=37&p4=239&p5=235&p6=152&p7=770&p8=43&p9=240))
 **Place:** [Zoom link](https://ucl.zoom.us/j/92511115251?pwd=OUNnN3VCTXU0VjFGc0tqYTZtZkhodz09)
**Previous Meeting:** issue #12 
 **Who can come?:** Anyone. No need to say anything unless you'd like to. If you'd like to contribute, please join Github.

_Attendees:_ Prof Matthew Todd (UCL), Dr Eve Carter (UCL), Dr Claudia Tredup (Goethe-University Frankfurt), Dr Nico Braeuer (Nuvisan), Anna Girtle (UCL)

_Decks_: [Eve's Presentation](https://github.com/StructuralGenomicsConsortium/CNP5-PLCZ1/files/14054274/2023-10-10.open.meeting.pptx)

### Agenda:

- Update from Madison Edwards, [@EveCarter](https://github.com/EveCarter), and Opher Gileadi

**In meeting:**

RECAP: Madison purified chicken, mouse, and macaque PLCz1. The chicken protein came out very clean, whereas the mouse protein tends to dimerize and the macaque protein is not consistently reproducible at this time.
- Nuvisan tested these proteins in their IP-one assay and they all showed activity. Notably, the chicken protein was found to remain active after 2 hours at room temperature, an important quality for use in DEL screens.
- Karl injected Madison’s human PLCz1 (with chaperone), mouse PLCz1 (monomer and dimer), and chicken PLCz1 into mouse eggs and they all gave calcium oscillations. This is encouraging as it suggests they may be functional in vivo.

RECAP: Madison performed TSAs with IP3 and found no stabilization.
- Madison tried 3 new compounds in the TSA (YM-26734, manoalide, ATA), all of which seem to slightly destabilize the protein. These results are a bit strange as they are opposite of what we expected due to Nuvisan’s results.

RECAP: Eve has been working on the Aldol assay.
- Eve has been working on optimizing the concentration of free Ca2+ in the assay buffer. She needs to repeat the experiment but preliminary results show fairly consistent activity from 10-90µM Ca2+ with a spike at 110µM. She wants to determine whether 110µM is the optimal concentration or if it is an outlier.

**Future work:**

- Opher to do last attempt to express PLCz1 in HEK.
- Madison and Nuvisan to send proteins (chicken, macaque, Nuvisan’s human PLCd and inactive PLCz) for DEL-ability review before sending for DEL screen.
- Madison to test Nuvisan’s hits from HTS in TSA.
- Eve to repeat some Ca2+ concentrations in Aldol assay and test Nuvisan’s PLC inhibitors as they so far have no good correlation between XY-69 and IP-one assay. She will also test Matilda’s compounds to confirm the assay is working as expected. 

_L'esprit de l'escalier_
If you'd like to follow up after the meeting, please comment below. You can also email, but please be clear if anything in the email should not be public domain - the default is open.

**Next meeting**: Tuesday 7th November, 2pm UK time

**Comment by mattodd** [comment]
Some key things from this meeting from my perspective @EveCarter @AnnaGirtle 
1) A nice general approach from Nico - if the compounds binding delta also bind zeta then it might be possible to use delta for the screening and initial hit exploration and then dial in the zeta selectivity later.
2) NMR is an option if it's working well for delta. At UCL we could screen with 19F or develop a binding assay if we had a weak binder containing 19F.
3) Do lipase panels exist, for counter-screening?
4) Thermal melt might not be the bast biophysical assay for the screen that is meant to be orthogonal to the biochemical assay
5) Great that Nuvisan are doing some crystallography trials. I wonder if we could bring Diamond to bear on this problem if extra resources are needed later.
