### ISSUE TITLE
PLCz1 Open Online Meeting - Tue Jan 9th

### ISSUE THREAD

**Issue by AnnaGirtle** [StructuralGenomicsConsortium/CNP5-PLCZ1#14]
**Date:** Tue January 9th 2024
 **Time:** 2pm UK time ([other times](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2024&month=1&day=9&hour=14&min=0&sec=0&p1=136&p2=250&p3=37&p4=239&p5=235&p6=152&p7=770&p8=43&p9=240))
 **Place:** [Zoom link](https://ucl.zoom.us/j/92511115251?pwd=OUNnN3VCTXU0VjFGc0tqYTZtZkhodz09)
**Previous Meeting:** issue #13 
 **Who can come?:** Anyone. No need to say anything unless you'd like to. If you'd like to contribute, please join Github.

_Attendees:_ Dr Eve Carter (UCL), Dr Claudia Tredup (Goethe-University Frankfurt), Prof Matthew Todd (UCL), Dr Nico Braeuer (Nuvisan), Anna Girtle (UCL), Prof Opher Gileadi (SGC), Dr Madison Edwards (Uni Toronto), Prof Al Edwards (Uni Toronto).

_Decks_: [Eve's presentation](https://github.com/StructuralGenomicsConsortium/CNP5-PLCZ1/files/14054026/2024-01-09.open.meeting.pptx)

### Agenda:

- Update from [@EveCarter](https://github.com/EveCarter)

**In meeting:**
Eve presented her work on the Aldol 518 assay. Chicken, mouse and human PLCz1 all seem to work with this assay, although there are slow kinetics. In particular, there seems to be a lag of ~5 h for chicken and mouse PLCz1 before fluorescence increases. Also, there has been some inconsistencies in the value of RFU recorded. Eve checked that the protein was not degrading from being freeze-thawed, and that the Aldol 518 substrate stock was also not degrading. It seems that running the assay with 2x the buffer concentrations gives higher values of RFU, but the kinetics are still slow. Another issue is the evaporation of the assay as the plate is left uncovered inside the plate reader.

X-Chem have performed a DELability screen on Chicken PLCζ1, Mouse PLCζ1, Inactive human D202R PLCζ1, Inactive human H170A_H215A PLCζ1and Human PLCδ1. This assay was accidentally run in a buffer containing 200mM sucrose and 200mM arginine. Eve checked these conditions in the Aldol 518 assay and found that they inactivate the protein.

To do:

- [x] Eve will discuss the results of the Aldol 518 assay with Matilda Katan, Tom Bunney and Anna Thrun.
- [ ] Repeat DELability screen in a different buffer.

_L'esprit de l'escalier_
If you'd like to follow up after the meeting, please comment below. You can also email, but please be clear if anything in the email should not be public domain - the default is open.

**Next meeting**: 
Tues 6th Feb 2024

**Comment by mattodd** [comment]
To digest and add to wiki at some point: https://www.preprints.org/manuscript/202312.1738/v1
Thanks Madison for the ping.
