### ISSUE TITLE
Most similar proteins to PLCz1

### ISSUE THREAD

**Issue by EveCarter** [StructuralGenomicsConsortium/CNP5-PLCZ1#2]
There appears to be little information on PLCz1 that will help us design small molecule inhibitors (no crystal structure, no known inhibitors etc.) therefore we are looking at similar proteins to get some ideas.

Searching the human PLCs using [ChemBioPort](https://chembioport.thesgc.org/) (and relevant [paper](https://academic.oup.com/database/article/doi/10.1093/database/baac088/6718166)) did not provide any known inhibitors or chemical probes, and the only ligands seen in the crystal structures appeared trivial.

 Out of the other PLCs, delta 1 is known to have the greatest sequence identity and similarity. However, PLCd1 has a key PH (pleckstrin homology) domain, which PLCz1 does not have. Therefore is it fair to compare these?
![image](https://user-images.githubusercontent.com/112560282/193291501-15bdeaad-6a24-4e43-8b55-aa3153cf2be8.png)
Sequence identity (blue) and similarity (red) between mammalian PLC isoforms [doi:10.1242/dev.129.15.3533](https://journals.biologists.com/dev/article/129/15/3533/41784/PLC-a-sperm-specific-trigger-of-Ca2-oscillations)

Are there any other similar proteins we should be looking into?

**Comment by mattodd** [comment]
It's interesting @EveCarter that there is so little similarity. Yes, I wonder if there is something else in a different family that has a more similar active site, at least. I think you mentioned that Levon (will ask him to join here) appears to have done the Alphafold comparison [here](https://github.com/StructuralGenomicsConsortium/CNP5-PLCZ1/blob/main/FIle%20Diary/2022/Feb%202022%20Levon%20Protein%20Expression%20Update/PATL2_ABHD2_PLC-zeta_FIGLA_TestX_v2.pdf) and I wonder if there's a "similarity tool" on that platform?

Will try to ping Matthieu Schapira for thoughts.

I guess we'd need to consider phospholipase inhibitors more broadly as the next step, e.g. your observation about the possibility of something like sphingomyelin.

**Comment by EveCarter** [comment]
Closing as this the conversation has finished. More information is on the wiki.
