### ISSUE TITLE
PLCz1 Open Online Meeting - Tue Nov 1st

### ISSUE THREAD

**Issue by mattodd** [StructuralGenomicsConsortium/CNP5-PLCZ1#3]
**Date**: Tue Nov 1st 2022
**Time**: 2pm UK time ([other times](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2022&month=11&day=1&hour=14&min=0&sec=0&p1=43&p2=136&p3=37&p4=771&p5=235&p6=152&p7=770&p8=250&p9=196&p10=240))  
**Place**: https://ucl.zoom.us/j/95337925999  
**Recording**:  https://youtu.be/2fenn03sj2M
**Previous Meeting**: none
**Who can come?**: Anyone. No need to say anything unless you'd like to. If you'd like to contribute, please join Github.

Attendees: @EveCarter, @mattodd (UCL), Prof Karl Swann (Uni Cardiff), Prof Al Edwards, @Lev-Ha, Dr Madison Edwards (Uni Toronto), Dr Claudia Tredup (Goethe-University Frankfurt).

_Apologies_: 

_Decks_: Please @StructuralGenomicsConsortium/cnp5-plcz1 remember that if you share slides/info, to drag and drop those into a comment on this page, below. _Very easy and saves @mattodd having to pester you._

**Agenda**:

### 1) Protein Production

Update from Madison Edwards and @Lev-Ha, slides are posted below. **In meeting:** Consensus is that protein handling is difficult. Diluting the protein can be problematic, and it should be kept at no less than 1 mg mL-1. Freeze in glycerol. There would be some value in an exploration of buffers/salts to achieve stabilisation (though clearly these may need to be dialysed out for the protein to be used) and Madison has done some of this already. Ammonium sulfate apparently precipitates the protein.
@Lev-Ha said that protein pellet could be send to UCL for us to try to purify here.
If protein production in HEK293 cells work, we can also outsource production. Claudia has already looked into this.

### 2) Best Possible Focussed Inhibitor Libraries

Update to what's been discussed in #2. **In meeting**: There is a commercial inhibitor sometimes used (U-73122) but it appears to operate on calcium ion oscillations via a means that is not inhibition of PLC. So it's not very useful for our purposes. 
Notice that *binders* rather than inhibitors are still useful for possible fluorescence polarisation displacement assays. Also binders can gibe key info about location of binding by other compounds in e.g. DEL and ASMS screens.

- [x] @EveCarter and @mattodd to set up a call with Tim Richardson to discuss possible starting points for libraries.

### 3) Assays

Update to what's been discussed in #1. In meeting: Karl mentioned that even if the protein behaves in vitro there will be a need to investigate its function in eggs themselves.

- [x] @EveCarter to set up call with Sondek to discuss availability of the assay reagents, or other possible reagents.
- [x] Aled Edwards offered to reach out to Abcam to ask about the nature of their assay, so that we could see if there was a way we could collaborate on this project. Update: Eve has now got this information from Abcam.

### 4) AOB

Does anyone else need to be invited to these meetings to grow the group productively?

- [x] @mattodd to set up meeting with Matilda Katan at UCL to discuss approaches to this project that may be informed by Matilda's work on PLCg.
- [x] @mattodd will forward this page to the Nuvisan team. Important that we continue to interact regularly with Nuvisan (e.g. sharing this page with the team) to ensure maximal interchange of data and ideas. 
- [x] Someone (**TBD**) to reach out to those people involved in mouse KO studies for the generation of antibodies. Karl to forward names of those people most likely to be maintaining a knock-out mouse line for PLCz1, for the generation of antibodies. The mouse protein is not identical to the human, but it's a start. **After meeting**: Karl kindly forwarded: John Parrington in Oxford made the PLCz KO mice, as did Masa Ikawa in Osaka Uni, Japan. It's not clear if the colonies are active, but we can ask. A way round this issue might be to just compare sperm or testis with other tissues from WT mice?  Not as neat , but easy.

**Next Meeting**
Tue Dec 6th 2pm UK time OK for everyone?

**L'esprit de l'escalier**
If you'd like to follow up after the meeting, please comment below. You can also email, but please be clear if anything in the email should not be public domain - the default is open.

**Comment by EveCarter** [comment]
Here are my slides from the meeting:
[2022-11-01 open meeting 1.pptx](https://github.com/StructuralGenomicsConsortium/CNP5-PLCZ1/files/9911190/2022-11-01.open.meeting.1.pptx)

**Comment by EveCarter** [comment]
Closing as the actions from this meeting have been completed.
