### ISSUE TITLE
PLCz1 Open Online Meeting - Tue May 2nd

### ISSUE THREAD

**Issue by AnnaGirtle** [StructuralGenomicsConsortium/CNP5-PLCZ1#8]
**Date:** Tue May 2nd 2023
 **Time:** 2pm UK time ([other times](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2023&month=5&day=2&hour=13&min=0&sec=0&p1=136&p2=250&p3=37&p4=239&p5=235&p6=152&p7=770&p8=43&p9=240))
 **Place:** [Zoom link](https://ucl.zoom.us/j/93994523856?pwd=OXh6NFo4VlozUHliVkJNNmxjbldKQT09)
**Previous Meeting:** issue #7 
 **Who can come?:** Anyone. No need to say anything unless you'd like to. If you'd like to contribute, please join Github.

_Attendees:_ Prof Matthew Todd (UCL), Dr Eve Carter (UCL), Prof Matilda Katan (UCL), Dr Madison Edwards (Uni Toronto), Prof Karl Swann (Uni Cardiff), Prof Al Edwards (SGC), Prof Opher Gileadi (SGC), Dr Nico Braeuer (Nuvisan), Dr Anna Thrun (Nuvisan), Dr Anders Friberg (Nuvisan), Anna Girtle (UCL)

_Decks_: [Opher's presentation](https://github.com/StructuralGenomicsConsortium/CNP5-PLCZ1/files/11373815/Protein.engineering.of.PLCZ1.Update.May.2.2023.pptx)

### Agenda:

**1) Protein Production**
- Update from Opher Gileadi

**In meeting:** Opher described his work on PLCz1 protein engineering. He has been using 3 main approaches in _E.coli_: high-throughput split GFP-based screening of engineered PLCz1 mutants, increasing structural stability with [PROSS](https://fleishmanlab.weizmann.ac.il/servers/pross/step/pross-terms/)-identified mutants, and scanning loop deletions to see if the X-Y linker can be made more stable. SDS PAGE of total lysates show PLCz1 is being expressed, however, when attempting to purify the protein, only GroEL was observed, similar to previous results from Madison.

Dalia and Peter in Toronto have performed mammalian expression of hPLCz1 that is codon optimised for humans. All bands seen in a western blot are shorter than expected, with the largest appearing to correspond to the loss of the EF hands (this is just through mass on a gel, mass spec has not been performed). Opher plans to build on this work by performing mammalian expression with a different vector (pLexm) and a strep (rather than FLAG) tag.

There was some discussion about doing a pull-down assay to identify an interaction partner of PLCz1, which may be required to produce soluble protein. Karl mentioned that there is some evidence that PLCz1 will work in mature frog eggs, so a potential reaction could be to mix a lysate from mature frog oocytes with lysate from FLAG tagged PLCz1-expressing HEK293 cells, allow them to incubate, then pull down PLCz1 with any interaction partner.

The disordered loop between the X and Y domains was discussed, as Opher has looked at a range of different deletions in this region. If protein expression is improved without the loop, there may be some early-stage drug discovery uses, even if it is inactive in cells. 

**Next meeting:** Tuesday 6th June, 2pm UK time

_L'esprit de l'escalier_
If you'd like to follow up after the meeting, please comment below. You can also email, but please be clear if anything in the email should not be public domain - the default is open.

**Comment by ogileadi** [comment]
[Protein engineering of PLCZ1 Update May 2 2023.pptx](https://github.com/StructuralGenomicsConsortium/CNP5-PLCZ1/files/11373542/Protein.engineering.of.PLCZ1.Update.May.2.2023.pptx)
