### ISSUE TITLE
PLCz1 Open Online Meeting - Tue June 6th

### ISSUE THREAD

**Issue by AnnaGirtle** [StructuralGenomicsConsortium/CNP5-PLCZ1#9]
**Date:** Tue June 6th 2023
 **Time:** 2pm UK time ([other times](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2023&month=6&day=6&hour=13&min=0&sec=0&p1=136&p2=250&p3=37&p4=239&p5=235&p6=152&p7=770&p8=43&p9=240))
 **Place:** [Zoom link](https://ucl.zoom.us/j/92810058430?pwd=R2lnT3JjY2tLWHAyMDJ6WjgranpaZz09)
**Previous Meeting:** issue #8 
 **Who can come?:** Anyone. No need to say anything unless you'd like to. If you'd like to contribute, please join Github.

_Attendees:_ Prof Matthew Todd (UCL), Dr Eve Carter (UCL), Prof Matilda Katan (UCL), Dr Madison Edwards (Uni Toronto), Prof Karl Swann (Uni Cardiff), Dr Ralf Lesche (Nuvisan), Anna Girtle (UCL)

_Decks_: 

### Agenda:

**1) Protein Production**
- Update from Madison Edwards and [@EveCarter](https://github.com/EveCarter)

**In meeting:**

Eve shared that Opher's group has managed to get full length PLCz1 by sub-cloning the codon-optimized gene from Toronto in mammalian cells with a slightly different expression vector and tag than has been used previously. The results look positive but have only been tested by Western blot, so the goal for the next month is to check stability and solubility.

Madison has been working on trying to express animal PLCz1 (mouse E8, chicken E9, macfa E10) using SF9/baculovirus system. The proteins were purified using nickel beads and anti-flag Western blot gives a band at 70 kDa that is believed to be from flag-tagged PLCz1. In all experiments to date the PLCz1s have been running lower than expected (around 70 instead of 75-78 kDa). Anti-flag Western blot confirmed that the bands at 70 kDa were in fact PLCz1 in the species tested. This result was further verified by treatment of mouse and macfa proteins with TEV protease followed by running through a reverse nickel column. These proteins were then sent to Nuvisan for activity testing. If they are found to be active, Madison will pursue the macfa PLCz1 as it is 95-96% similar to the human version.

Karl mentioned that we can microinject macfa PLCz1 into mouse eggs to ensure it behaves similarly to the human version, though past results in his lab suggest while it is less potent, it is functional. He also suggested concentrating samples as much as possible (>1 mg/mL) before snap freezing to help maintain stability. Matilda suggested it might be useful to check the equilibria and organization between monomers and how concentration might influence that.

Ralf shared that Nuvisan has produced protein of sufficient quality and has begun a high throughput screening campaign searching for small molecules. They are currently cascading down the hits using biochemical assays but hope to set up mouse assays in the long term.

**2) Any other business**

_L'esprit de l'escalier_
If you'd like to follow up after the meeting, please comment below. You can also email, but please be clear if anything in the email should not be public domain - the default is open.

**Comment by mattodd** [comment]
Thanks for posting @AnnaGirtle ! This one's not in my Outlook calendar. Two possibilities - I'm being dumb, or the invitation for this meeting hasn't been sent out yet (or the series invitation has run out). Just let me know which it is!

**Comment by AnnaGirtle** [comment]
Sorry @mattodd, I was swamped with exams but I just sent out the invitation, and Eve is helping me with the updates from the last meeting. I promise to have the invitation out sooner next month.

**Comment by mattodd** [comment]
No problem at all - thanks so much for taking care of this, it really helps. And yes any and all updates from the last meeting from Eve would be great. Hope the exams were OK.
